"use server"
import { createClient } from "@/utils/supabase/server"

// List of possible drugs with their details
const drugs = [
    {
        name: 'Amoxicillin',
        label: 'Antibiotic',
        price: '20.00',
        quantity: '30',
        ndc: '00069-1520-68',
        dosage: '500 mg twice a day',
        drugformid: 'DF001',
        drugcategoryid: 'DC001',
        drugclassid: 'CL001',
        drugtypeid: 'DT001',
        agegroupid: 'AG001',
        refillable: true,
        refilllimit: '2',
        tierone: 'Yes',
        tiertwo: 'No',
        tierthree: 'No',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'Yes',
        active: true,
        minquantity: '10',
        maxquantity: '100',
        quantityallowed: '30'
    },
    {
        name: 'Ibuprofen',
        label: 'Pain reliever',
        price: '10.00',
        quantity: '60',
        ndc: '00093-1044-06',
        dosage: '200 mg every 4-6 hours',
        drugformid: 'DF002',
        drugcategoryid: 'DC002',
        drugclassid: 'CL002',
        drugtypeid: 'DT002',
        agegroupid: 'AG002',
        refillable: true,
        refilllimit: '5',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'No',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '20',
        maxquantity: '200',
        quantityallowed: '60'
    },
    {
        name: 'Lisinopril',
        label: 'Blood pressure medication',
        price: '15.00',
        quantity: '90',
        ndc: '00093-7212-10',
        dosage: '10 mg once a day',
        drugformid: 'DF003',
        drugcategoryid: 'DC003',
        drugclassid: 'CL003',
        drugtypeid: 'DT003',
        agegroupid: 'AG003',
        refillable: true,
        refilllimit: '3',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'Yes',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '30',
        maxquantity: '300',
        quantityallowed: '90'
    }, 
    {
        name: 'Metformin',
        label: 'Diabetes medication',
        price: '25.00',
        quantity: '60',
        ndc: '00093-0102-05',
        dosage: '500 mg twice a day',
        drugformid: 'DF004',
        drugcategoryid: 'DC004',
        drugclassid: 'CL004',
        drugtypeid: 'DT004',
        agegroupid: 'AG004',
        refillable: true,
        refilllimit: '4',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'Yes',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '20',
        maxquantity: '240',
        quantityallowed: '60'
    },
    {
        name: 'Atorvastatin',
        label: 'Cholesterol medication',
        price: '30.00',
        quantity: '30',
        ndc: '00093-5710-56',
        dosage: '10 mg once a day',
        drugformid: 'DF005',
        drugcategoryid: 'DC005',
        drugclassid: 'CL005',
        drugtypeid: 'DT005',
        agegroupid: 'AG005',
        refillable: true,
        refilllimit: '3',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'No',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '10',
        maxquantity: '90',
        quantityallowed: '30'
    },
    {
        name: 'Albuterol',
        label: 'Asthma inhaler',
        price: '35.00',
        quantity: '1',
        ndc: '0173-0479-00',
        dosage: '2 puffs every 4-6 hours as needed',
        drugformid: 'DF006',
        drugcategoryid: 'DC006',
        drugclassid: 'CL006',
        drugtypeid: 'DT006',
        agegroupid: 'AG006',
        refillable: true,
        refilllimit: '6',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'Yes',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'Yes',
        active: true,
        minquantity: '1',
        maxquantity: '6',
        quantityallowed: '1'
    },
    {
        name: 'Levothyroxine',
        label: 'Thyroid hormone',
        price: '40.00',
        quantity: '30',
        ndc: '00093-2512-05',
        dosage: '50 mcg once a day',
        drugformid: 'DF007',
        drugcategoryid: 'DC007',
        drugclassid: 'CL007',
        drugtypeid: 'DT007',
        agegroupid: 'AG007',
        refillable: true,
        refilllimit: '2',
        tierone: 'Yes',
        tiertwo: 'No',
        tierthree: 'No',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '10',
        maxquantity: '90',
        quantityallowed: '30'
    },
    {
        name: 'Omeprazole',
        label: 'Acid reflux medication',
        price: '18.00',
        quantity: '30',
        ndc: '00173-0479-55',
        dosage: '20 mg once a day',
        drugformid: 'DF008',
        drugcategoryid: 'DC008',
        drugclassid: 'CL008',
        drugtypeid: 'DT008',
        agegroupid: 'AG008',
        refillable: true,
        refilllimit: '3',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'No',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '15',
        maxquantity: '90',
        quantityallowed: '30'
    },
    {
        name: 'Amlodipine',
        label: 'Blood pressure medication',
        price: '22.00',
        quantity: '30',
        ndc: '00603-2108-02',
        dosage: '5 mg once a day',
        drugformid: 'DF009',
        drugcategoryid: 'DC009',
        drugclassid: 'CL009',
        drugtypeid: 'DT009',
        agegroupid: 'AG009',
        refillable: true,
        refilllimit: '3',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'Yes',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '10',
        maxquantity: '90',
        quantityallowed: '30'
    },
    {
        name: 'Hydrochlorothiazide',
        label: 'Diuretic',
        price: '15.00',
        quantity: '30',
        ndc: '00093-7401-56',
        dosage: '25 mg once a day',
        drugformid: 'DF010',
        drugcategoryid: 'DC010',
        drugclassid: 'CL010',
        drugtypeid: 'DT010',
        agegroupid: 'AG010',
        refillable: true,
        refilllimit: '4',
        tierone: 'Yes',
        tiertwo: 'Yes',
        tierthree: 'No',
        tierfour: 'No',
        tierfive: 'No',
        erxrequired: 'No',
        active: true,
        minquantity: '10',
        maxquantity: '120',
        quantityallowed: '30'
    },
    // Add more drugs as needed
];

// Function to randomly select a drug from the list
function getRandomDrug() {
    const randomIndex = Math.floor(Math.random() * drugs.length);
    return drugs[randomIndex];
}

export async function addPrescriptions(patientId: string) {
    const randomDrug = getRandomDrug();
    const { error } = await createClient().from('prescriptions').insert({
        patient_id: patientId,
        name: randomDrug.name,
        label: randomDrug.label,
        price: randomDrug.price,
        quantity: randomDrug.quantity,
        ndc: randomDrug.ndc,
        dosage: randomDrug.dosage,
        drugformid: randomDrug.drugformid,
        drugcategoryid: randomDrug.drugcategoryid,
        drugclassid: randomDrug.drugclassid,
        drugtypeid: randomDrug.drugtypeid,
        agegroupid: randomDrug.agegroupid,
        refillable: randomDrug.refillable,
        refilllimit: randomDrug.refilllimit,
        tierone: randomDrug.tierone,
        tiertwo: randomDrug.tiertwo,
        tierthree: randomDrug.tierthree,
        tierfour: randomDrug.tierfour,
        tierfive: randomDrug.tierfive,
        erxrequired: randomDrug.erxrequired,
        active: randomDrug.active,
        minquantity: randomDrug.minquantity,
        maxquantity: randomDrug.maxquantity,
        quantityallowed: randomDrug.quantityallowed,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    });

    if (error) {
        console.log('Error inserting prescription:', error);
    } else {
        console.log('Prescription added successfully');
    }
}
